# Site settings
title: Nimble Octopodes 
header-img: img/home-bg.png
email: lem.alexander@gmail.com
copyright_name: alexanderlem
description: > # this means to ignore newlines until "baseurl:"
  My Coding Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alexanderlem
learn_profile: alexanderlem
email_username: lem.alexander@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
